{
 "title": "Envoy Gateway Global",
 "description": "Envoy Gateway monitoring Dashboard with exported metrics.",
 "tags": [ "Control Plane" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(watchable_depth,namespace)"
    }
   },
   {
    "name": "Runner",
    "query": {
     "query": "label_values(watchable_depth,runner)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Watching Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration Bucket: $Runner",
   "type": "bargauge",
   "description": "How long in seconds a subscribed watchable is handled.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (watchable_subscribe_duration_seconds_bucket{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(runner) (watchable_subscribe_duration_seconds_sum{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max by(runner) (watchable_subscribe_duration_seconds_sum{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "stat",
   "description": "Current depth of watchable map.",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(runner) (watchable_depth{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (watchable_subscribe_total{runner=\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(watchable_subscribe_total{runner=\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Status Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Recovered Panics",
   "type": "stat",
   "description": "Total number of panics recovered in the system.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(watchable_panics_recovered_total{namespace=\"$Namespace\"})",
     "legendFormat": "Recovered Panics"
    }
   ]
  },
  {
   "title": "Total Duration Bucket",
   "type": "bargauge",
   "description": "How long a status update takes to finish for all Kind.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (status_update_duration_seconds_bucket{namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (rate(status_update_duration_seconds_sum{namespace=\"$Namespace\"}[5m])) / sum by(kind) (rate(status_update_duration_seconds_count{namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "p99 Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, kind) (rate(status_update_duration_seconds_bucket{namespace=\"$Namespace\"}[5m])))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "p50 Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, kind) (rate(status_update_duration_seconds_bucket{namespace=\"$Namespace\"}[5m])))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "description": "Total number of status updates by object kind.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kind) (status_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (status_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "xDS Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Snapshot Creation Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xds_snapshot_create_total{namespace=\"$Namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(status) (xds_snapshot_create_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Finished Stream",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(xds_stream_duration_seconds_bucket{namespace=\"$Namespace\", isDeltaStream=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "stat",
   "description": "Maximum duration seconds for finished xDS delta stream connection.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "xds_stream_duration_seconds_sum{namespace=\"$Namespace\", isDeltaStream=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Duration",
   "type": "stat",
   "description": "Minimum duration seconds for finished xDS delta stream connection.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "xds_stream_duration_seconds_sum{namespace=\"$Namespace\", isDeltaStream=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Total",
   "type": "timeseries",
   "description": "Total number of xds snapshot cache updates by node id.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(nodeID) (xds_snapshot_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (xds_snapshot_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  { "title": "Infrastructure Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Total Apply Duration Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (resource_apply_duration_seconds_bucket{namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Apply Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (rate(resource_apply_duration_seconds_sum{namespace=\"$Namespace\"}[5m])) / sum by(kind) (rate(resource_apply_duration_seconds_count{namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Apply Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, kind) (rate(resource_apply_duration_seconds_bucket{namespace=\"$Namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 Apply Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, kind) (rate(resource_apply_duration_seconds_bucket{namespace=\"$Namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Applied Resources",
   "type": "timeseries",
   "description": "Total number of applied resources sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by(kind) (resource_apply_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applied Resources Status",
   "type": "timeseries",
   "description": "Total number of applied resources that succeed sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
   "targets": [
    {
     "expr": "sum by(status) (resource_apply_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Applied Infrastructures",
   "type": "timeseries",
   "description": "Total number of applied resources sumed by infra name.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(name) (resource_apply_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delete Duration Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (resource_delete_duration_seconds_bucket{namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Delete Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (rate(resource_delete_duration_seconds_sum{namespace=\"$Namespace\"}[5m])) / sum by(kind) (rate(resource_delete_duration_seconds_count{namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Delete Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, kind) (rate(resource_delete_duration_seconds_bucket{namespace=\"$Namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 Delete Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, kind) (rate(resource_delete_duration_seconds_bucket{namespace=\"$Namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deleted Resources",
   "type": "timeseries",
   "description": "Total number of deleted resources sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by(kind) (resource_delete_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Resources Status",
   "type": "timeseries",
   "description": "Total number of deleted resources that succeed sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "targets": [
    {
     "expr": "sum by(status) (resource_delete_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deleted Infrastructures",
   "type": "timeseries",
   "description": "Total number of deleted resources sumed by infra name.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(name) (resource_delete_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wasm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Cache Entries",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wasm_cache_entries{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Lookups",
   "type": "stat",
   "description": "Total number of Wasm remote fetch cache lookups.",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hit) (wasm_cache_lookup_total{namespace=\"$Namespace\"})",
     "legendFormat": "hit={{hit}}"
    }
   ]
  },
  {
   "title": "Cache Remote Fetches",
   "type": "stat",
   "description": "Total number of Wasm remote fetches and results.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (wasm_remote_fetch_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(wasm_remote_fetch_total{namespace=\"$Namespace\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}
{
 "title": "Envoy Global",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [ "Data Plane" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (envoy_server_uptime{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_heap_size{namespace=~\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_allocated{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "DownStream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[5m]))",
     "legendFormat": "Envoy HTTP Downstream Rq total"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_http_downstream_cx_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(envoy_http_downstream_rq_time_bucket[5m])))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(envoy_http_downstream_rq_time_bucket[5m])))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(envoy_http_downstream_rq_time_bucket[5m])))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_listener_downstream_cx_active{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TCP Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_tcp_downstream_cx_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TCP Downstream Bytes Rx/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_tcp_downstream_cx_rx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TCP Downstream Bytes Tx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_tcp_downstream_cx_tx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "UpStream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream RPS",
   "type": "timeseries",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_rq_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$Namespace\",}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$Namespace\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$Namespace\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$Namespace\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Upstream Bytes Rx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_cx_rx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Upstream Bytes Tx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_cx_tx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Upstream Response Codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream 2xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"2\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"3\"}[5m]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint Percentage Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\"}) by (namespace) / avg(envoy_cluster_membership_total{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_cluster_membership_total{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_cluster_membership_healthy{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_cluster_membership_total{namespace=~\"$Namespace\"}) - sum by(namespace) (envoy_cluster_membership_healthy{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}