promtail:
  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 514
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 172.31.1.40

  config:
    clients:
    - url: http://loki-gateway/loki/api/v1/push  # default value
    snippets:
      pipelineStages:
      - static_labels:      # static labels to be added to the stream
          cluster: orange
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
            labels:
              job: syslog
          relabel_configs:
            - source_labels:
                - __syslog_message_hostname
              target_label: hostname

            # example label values: kernel, CRON, kubelet
            - source_labels:
                - __syslog_message_app_name
              target_label: app

            # example label values: debug, notice, informational, warning, error
            - source_labels:
                - __syslog_message_severity
              target_label: level
