apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argo
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
    notifications.argoproj.io/subscribe.on-sync-running.slack: argo
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
  name: nfs-pgsql
  namespace: argocd
spec:
  destination:
    namespace: nfs-atlas
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: apps/nfs-atlas
    repoURL: https://github.com/germanium-git/argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
