apiVersion: v2
name: rancher-umbrella-chart
description: An Umbrella Helm Chart to install Rancher
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: rancher
    version: 2.7.9
    repository:  https://releases.rancher.com/server-charts/latest
