apiVersion: v2
name: umbrella-chart
description: An Umbrella Helm Chart for metallb
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: metallb
    version: 0.14.5
    repository: https://metallb.github.io/metallb
