apiVersion: v2
name: pgsql
description: An Umbrella Helm Chart for postgresql
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 18.1.3
    repository: https://charts.bitnami.com/bitnami
