postgresql:
  primary:
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
      runAsUser: 1002
      runAsGroup: 1000
    persistence:
      storageClass: "nfs-atlas"
  nameOverride: "awx"
