apiVersion: v2
name: umbrella-chart
description: An Umbrella Helm Chart for Loki
type: application
version: 0.1.0
appVersion: "3.5.7"

dependencies:
  - name: loki
    version: 6.46.0
    repository:  https://grafana.github.io/helm-charts
