apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: germanium-prod-cert
  namespace: default
spec:
  secretName:  germanium-cz-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.germanium.cz"
  dnsNames:
  - "germanium.cz"
  - "*.germanium.cz"
