apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: germanium-staging-cert
  namespace: default
spec:
  secretName:  germanium-cz-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.germanium.cz"
  dnsNames:
  - "germanium.cz"
  - "*.germanium.cz"
