apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-staging-cert
  namespace: default
spec:
  secretName:  local-germanium-cz-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.germanium.cz"
  dnsNames:
  - "local.germanium.cz"
  - "*.local.germanium.cz"
