apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgA17UGXyWu9tOpurg9goP7MyRvC2eWSQl94bRLNHIr3LZZsRC2ytkHORzOn9iN6nAACiLCcwtw7Q3C0iJ8nzrS8I8nmIIPHc9rQz/haCzrzBm/QAH4FPMC08HyELu0VReKm5YwNBQfMVpyHwWmzEKXw2bdfLdUwq/yrC2B72xnGgJ7g6INzT0bfpfODcIyvme8so6EZ2qFUAx22OXJ/3qnS57RCxuOcXtGeV1qeKEEYIv8k4iCJ9sq0LurvN+neUoPUXunEnOZwuls/4MkYHt0n9sZz1jgTdOAO5WIsOjRBor9y9v0GYKu77G3e29FDooDQWCC85hVYBMj6fcYfO9Rfqa5//TnMcV+LN9s62i0K01WbFWW6bNbsc9m79jVDOG3xMFgLV+JHpL9WxNvqcmYYg+837TSDRTpjCdWIvTR1XzT1LoAD8xcpZtd7S4HeXgFipmYMOfUgU/JPaWLKppN7kf+W2NGHjkgOi0tO8Dg1rT30PhVRJL/LPxcG/zKciG6Aw5GI/6pG4/ZZohJeV89mDuqcUIm3iD4We98uv2GELWoMjkH3diyYt9x9eHeV/Ls+DHKQ3WvxSKwmAhiglp8JB2DzqAa2GM+l1u08zdb3zvCm7Szn2BczC2OHdq6wqZkXv0XvxPEA0fkCIB8FJdR9xDazOgJL5TR+SyxZOYTm5pZwhhvY2DPtnvEe7G79dZUnEHLiWtpOlHJFEtw6C1Qv7zbQi2+k6Ches6iJ+rtG7AAWsOvXboTL
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
