apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argo
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
    notifications.argoproj.io/subscribe.on-sync-running.slack: argo
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/germanium-git/argocd
    path: apps/envoy-gateway
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml

  - repoURL: https://github.com/germanium-git/argocd
    path: apps/envoy-gateway/addons
    targetRevision: HEAD

  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
    jqPathExpressions:
    - .spec.versions[].selectableFields

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
