apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-postgresql
  namespace: paperless
spec:
  encryptedData:
    password: AgDL/F+++eUwRsNu86xpfjiEa6Y8UsLyiVnyqvp/T/FS/T9Hr/yjJ3Evic7BVJqpgwDiyQYOA3dpcnPhnB04F5ByWuLyaOnR3plCL4GVXgACPSYrO/enskOyQtNV0+ogYKENWqKVIU+Ma0sACW2S7WS2p7/vZYoCMJmtqoupC1Ndd4BP9GJehP4WFXgYrJlRQEhk2xgWJf6RU74z2LhYsHeOBykwRcMavFxH3We0Kz+Lh8/XGERpwfxZusf4mBt8daUqOh9ojP1QLLdKAK3STQmUMhAS1+WERSy4+coOOIg4pTh47/Rs2kiX0u4p52Dbnfa/vln38KEKjRlda7z5+NCLwCVc0HJvOFiu9EHmAvqlZmDVcMyAEfIKqCJt5SOI3A+y0xNUwm9Y80lQqRWvpvBCZ5O3QM6aaASZHut/b2CmGNF8kacPGnOPApCk2V3AXRvIRXToJ88+Tp/R5dZnduMGaAbbqcd+Od2n8Ptkgr/XSjAbIY2PeXi80s67FaJ6vDtSScQ+h4NuQfE1vswjoItQLDP4OkaaLoFQQoIeCuePB1No+ZDkjALAwkeLcTr1ZMbzXExtBi9zz/En3eoNXJIgYo3pih+/bWONfqHhuXVLMlgrXCCKKpv7XdR9iIUc7xaaM4rpxphpXi1Vnz8CKf5ewCiUTYlE/bzUXABDlgG4MxXyGq8rPkzJemmY/U3iwUW5/FmArZJ2dBg=
    postgres-password: AgBwsi8MHWsCWOBdwcnuOWH4YYXSjTGP43jW0FXxgYysMaRW0E6RZjRYOTdtw+HPvGDuYrLk+DtdSCtfGJZKRM5xKqZUDjWyqzQ/5t0+5Rr2rrl41Q9WZL3QhQuKpMxbXnJBZUWpzoUjifPeIOHGSgVosMM5nrx4uUg93atAsIux8bydAK8Idrd6ZxWlXbDUoBCgsUUt2K0ji1wugQAsLwdHNL9OGNO55z0m1tHR0JV9D1sKvwtAhhc5LRpofEWY9hPdf4owY19QX/kk9c09ZwiGIJEs34kt4G/tQObjmhexe6SxM5EpKQfztgINiYo7TGUXCBWpTXCcv3th4bPF4AOMApPjOkfN8uUnh91ruhK0wv7dYf5QK7WUvwO2601392D4nEddxVy7hHRvuTh2u3ffnHmOESIm343DDTyN4vqO5OwefGI/qHfRnEYtI8hoWpNVBjyKrbkSF0dj6I6xvHGC2/cmKN+yE630x2/QgDvY1HhX0kbBJhsHjQq9+DIR9+KA40OTCfZvmvnJmw3um7Kxw7ikBXZxh+7oVl4cgM8RyP4Dt42BzaVAcT9//Bh4wy8rqPAFHDGf68OOkDV+1F+tiWXGFnmzYZhBatjdjHvsZ7RiZNu9qiubpnqcEQ1LAzoQttPYbmPQv0LRYeMsc6ip9icCN/3dWdckI40Goa+Vu0o1nJkoNxLIrEwoLKq0SaCTWFq9waIajgF4AeOJfF5w7WUkxik=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-postgresql
      namespace: paperless

