apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secrets
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgCPLZ+fc0yZlhZPnikFcYdvO96IE7EJuS/x3PUzpQ7I3Z6WjworCrICqaIGAq6BsX3FDIZ+fxUVEL6WNyi+H5ZR5EIokr2Adnnw8W0rPBYWeo7a8nWs5tu4ZX7P53wfrOxvkiD+DJWSezpXetVmfkLzt7l6SQ6MX/7HC2I0OVQC0lxktJ8TFAMj0chUjhtb+uv9BWGsLpQAMQFwiTMugDH0JNVsxEZUcFpMBQ6B4RK2PqqC5QJwamn6OOheCKQMgFsSjtB1BpzZzQdT82dfh6gxzwP8ZSSxiL+2GMM8+4G0He0XW1CaDS4s78ZyfGaN5PRf6MqkkEZUohqGZfa5UybMVFhAvmzgCJzS7Od3J/4kv6slXQnHVau3DqqiIaIAhntDmUhEJzqzsDmUdJyaFy4zs8ZK2beXPRtpi0ES1OFBNk7mMZL/HXMoC2bsVUEr6CEy1sx+Nu+SCr2GN6BS6noUkpmAfRmD0wazRv/cW/C9aqNfgteA6gTbI3XI+g8FZ5hXJB7qMqqU1Br8yYEPuie0W81Juz3OD5Bhzt972hX3l2BjHo3DMH1UXRg4G+yHNgAhAN7/9+3A1Sl4lUUWIm4JCMg2Pt6BEKmwJtQddN6ksxqu5QBu8KLtQ411l01bNXaCYUeaEJxWP90uzI8VhRNd5aLUP8SdGRWUjNQwjffppyG1N8faAhSsjVVPgvmZ4ymykCXWPgG9qc7FCSzeVL3eT4wwfg==
    PAPERLESS_SECRET_KEY: AgBvCzAi4tgyT5+x+UwO+2BEDaB1MpCD44T6t1hXNaPYDrKwjiwpg2KdcJndxeuANeKrh50AJW6g1KgQkmmiCyIP9JjL9jC+Ih9OX/Xr9V6QS9Ic7ZloO2h2xydjJykWXkJw7xQ/47p6Fwg4nFO7/x7APQyhn3ED1tDKVffLL4K8NaxuOz/Lhithncc8mmUtODQy65YQrCOEOcQEJssFSmi1yrfW4Qcku0sx+YRj0BID1OpJkGtZEdrdYqwso0qenkb/7a1ozZ8t5KnQbDXNx9tt2u8GV7DmOivVYO0cOg/l23FsWWtJYhptndxJ/nHW5oQH8DlI1KJ8v7QzU3n+CeKnBggNJORcSPmKrFhMx35r1cWhlnxdw2FnX8YXYPwh1FcqhxCqD19wsLPtCTyVYTUzaB5zTToIk/G+Z89VkpYuOMo6vdW8Yaj774E4fipL3GHF/HZPpGq3MtXLs+I+W0V4IyU1hMEpsYVa6Nkdf730G+PdV6lEihLyPVadbBxV/mEQkoO27Pzz7z+TXX2LpLyU9e39lSKiUTace1oOrKG3Zw/bylinnFQQoXVzPD6UveK8mfgONNh+CnD3qePDkJ15XecYYosqsMMkYrdGnrV+1YO8ZuLBVMrdeWGN/0vwtRyvmizRLh+NuYgnXVPozAJnrKAIVuqgWEYHJP7ojgXhKDdvcPxI6UZHFzNtX6ZGLn+u5AvQvbPCMhbw9LdWAXJVloMUcywBeCSaYzHy/PSG39eRUT+8exWnEx5Rva608+VXiCkpdCFF9nnhP086I+hC
  template:
    metadata:
      creationTimestamp: null
      name: paperless-secrets
      namespace: paperless

