---
apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-postgres-configuration
  namespace: awx
stringData:
  host: "pgsql-awx.pgsql.svc.cluster.local"
  port: "5432"
  database: postgres
  username: postgres
  password: <--- add your password here --->
  sslmode: disable
  type: unmanaged
type: Opaque
