awx-operator:
  AWX:
    spec:
      hostname: awx-operator
    # configurations for external postgres instance
    postgres:
      enabled: false
      host: "pgsql-awx.pgsql.svc.cluster.local"
      port: "5432"
      dbName: postgres
      username: postgres
      sslmode: disable
      type: unmanaged

  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: mysuperlongpassword
      secretName: my-admin-password
