external-dns:
  sources:
    - ingress
    - gateway-httproute

  policy: sync

  provider:
    name: cloudflare

  extraArgs:
    - --default-targets=172.31.1.34

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-external-dns
          key: apiKey
