traefik:
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
    kubernetesGateway:
      enabled: true
  gateway:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: "172.31.1.34"
    listeners:
      web:
        namespacePolicy:
          from: All
  ports:
    metrics:
      expose:
        default: true
