traefik:
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  ports:
    metrics:
      expose:
        default: true
