traefik:
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  experimental:
    kubernetesGateway:
      enabled: true
      namespacePolicy: All
      annotations:
        external-dns.alpha.kubernetes.io/target: "172.31.1.34"
  ports:
    metrics:
      expose:
        default: true
