traefik:
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  experimental:
    kubernetesGateway:
      enabled: true
      namespacePolicy: All
  ports:
    metrics:
      expose:
        default: true
