apiVersion: v2
name: umbrella-chart
description: An Umbrella Helm Chart for metrics-server
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: metrics-server
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
