apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  namespace: omada
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: https
      protocol: TCP
      port: 8043
      targetPort: 8043
    - name: app-discovery
      protocol: TCP
      port: 27001
      targetPort: 27001
    - name: udp-management
      protocol: UDP
      port: 19810
      targetPort: 19810
    - name: udp-discovery
      protocol: UDP
      port: 29810
      targetPort: 29810
    - name: tcp-manager-v1
      protocol: TCP
      port: 29811
      targetPort: 29811
    - name: tcp-adopt-v1
      protocol: TCP
      port: 29812
      targetPort: 29812
    - name: tcp-upgrade-v1
      protocol: TCP
      port: 29813
      targetPort: 29813
    - name: tcp-manager-v2
      protocol: TCP
      port: 29814
      targetPort: 29814
    - name: tcp-transfer-v2
      protocol: TCP
      port: 29815
      targetPort: 29815
    - name: tcp-rtty
      protocol: TCP
      port: 29816
      targetPort: 29816
  selector:
    app: omada-controller
