apiVersion: v2
name: umbrella-chart
description: An Umbrella Helm Chart
type: application
version: 2.5.4
appVersion: "2026.6.4"

dependencies:
  - name: esphome
    version: 2.5.4
    repository:  https://charts.alekc.dev/
