apiVersion: v1
kind: PersistentVolume
metadata:
  name: orange3-local-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-orange3
  local:
    path: /var/tmp/k8s-local-storage # Path to local storage on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - orange3 # Replace with your node name
