apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCIxYUOsb0xt3HkUklxKxvwFGzGKQOBrB/kkX0nJWZWlQtKRly2NnhBeJPcqdh4956nQZB64tLlmLe1erdsnNuBBYaWmWdmaOyx9dOPP3eUPwAlM+t03tNqkAeR8kcT/HbiobmYJEHi6IsnNg4h8xRZvRzU+sfunDn45N7XngksWUD1ct0xBL7goU35oVxU1FVrmAtfoGvFHCqGVqPowKQmhzkGYFouyMRTxp7FAWNbUjddA2NUiQ101hMnT8R0HUw3CwVd3YgBDdIF5XAFJDqS9iNI9JAt4axOmWyeLBgtpTyVw/sKujR30DHeUPAYx1czhBeoyUYUjj9DVZJwwPQ8v/omMbqAbTApIgJajStsqp7GjPdDa/0D1y7mytJIKWmlzrWpFV3coHDN2bvwdzgCn1LkaInNW3Fg9jM3HWY9I8xPAyCWQLfsTYxbddPdXdqMK6AG+MpazucW4Pv/XsEXWHS8rd3UJYxtlLXMSIm3OZ5VJdcBLzHvesHAZuHQ20QyBuUdnSp6Jb+jd/qEFeTvg8Ls7DOsjSXj5b1ZV0nEY2rfp4Or6ErhDmhZZM/kRin5LfbpN1KT1PPY7BGbkl1Zgld7O0I6iprwLBI1iWSHBsDZYGz00cjftZICqJMQzP4fzy5dpvdaLBk/cCRYuRwVpLMmYIL2xxAbGZqgt6PlP7hpxdH/AXQS7kV0/tgvB7Qr4xoDYX1zr09XiF0fK+5nQVX4fQIUzIMPhaVRlv/gUPGiqAob0I5W
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
