apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argo
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
    notifications.argoproj.io/subscribe.on-sync-running.slack: argo
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/promtail
    repoURL: https://github.com/germanium-git/argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
