apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBJlGHPoHP4JN2RRmOAM0HP9Ht+90quhm18Ab/Hu5s0C5U5NWYMi6D0l1JVr2NymjgLffqedfYqRbw7SOoeQ+2rkJRQfJsjiVWvNvWEAcY9a9Ycf6uwH2KySc8joKYGAql4kUG+gZrT6bjH3A5rgWKExHMDopZkCFc6s7+x2AkJSUpjrZA8CDdW0+EPWAxlVwV1vmD5zUa0vhBKBjhgWPAdv5zJBK+qM7x5JY7vuTQTuWzAgZMEwBCkPmvHxpQKOL6mjxK6rvQDJFiGXMEVcZWgTdEIIimwPMwr3eYYpqPw73Job/Ju1uPS+PNRcAEIsn6RrEiC7D1c+xmGe2pZ4sZWzwE22Da+WkWre6eO6hzn4qlpqHlHcV4FjubBwNGJcEdTOYJAINYDvuKpuFG0u1LFk811JIrJEW0rYYO9YZSGGhAw0GSRy2LzP6vHZhhy//68Qsm5zhpJvIphK3VRInSNKs2oT9kzQ3BAa3R9YmjCbvMAGsCS2R2D2oUy1vW29RqZ51ps0Q79oEWjs2wiUbTX214gaG0cgxELmNs8mvOkKteonh5eyqsPaeHTa2WYDBfHrkW8xCz4wdMuT7S1i1hCKsu09TOWxQkKh9kb3Ut0ekL+0DQLc2XZbgZgNPCaVPvh8eUsunBuPshjmC7ErJFC0Llp6o8IL7LwN4NwSl3hrhqsvt3fNj4dPwxqReizWjez2CGwGhw3qF71ObGhUmZ9SB4eJbe3HNS0cxMjTYX7g+NLIlm+WSaN4dUj0vxhF0KovQ5t+eu+hcQ=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
