apiVersion: v2
name: argocd-umbrella-chart
description: An Umbrella Helm Chart to install ArgoCD
type: application
version: 0.1.0
appVersion: "3.2.0"

dependencies:
  - name: argo-cd
    version: 9.1.4
    repository:  https://argoproj.github.io/argo-helm
